default:
  retry: 1
  interruptible: true

variables:
  GIT_DEPTH: 5
  GITHUB_TOKEN: $GITHUB_TOKEN
  DOCKER_DRIVER: overlay2
  REPOSITORY_NAME: bluex-web-next
  MASTER_REPO_NAMESPACE: 'bluex-labs/web'

stages:
  - test
  - build

try_build:
  stage: test
  image:
    name: node:18-slim
    entrypoint: [""]
  script:
    - AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY npm run deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

build_deployable:
  stage: build
  image:
    name: node:18-slim
    entrypoint: [""]
  script:
    - npm run deploy
  rules:
    - if: '$CI_PROJECT_NAMESPACE == $MASTER_REPO_NAMESPACE && $CI_COMMIT_BRANCH =~ /dev|main|hotfix/'
